"""remove permission column from note_shares

Revision ID: f024d01f2994
Revises: aef6ce5e012e
Create Date: 2025-09-14 15:30:39.469594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f024d01f2994'
down_revision = 'aef6ce5e012e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_shares', 'permission')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_shares', sa.Column('permission', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
